[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"


[[edge_functions]]
function = "redirect"
path = "/acecms"

[[edge_functions]]
function = "redirect"
path = "/acecms/*"

[[edge_functions]]
function = "redirect"
path = "/web-development"

[[edge_functions]]
function = "redirect"
path = "/web-development/*"

[[edge_functions]]
function = "redirect"
path = "/products/ace-project-management-software"

[[edge_functions]]
function = "redirect"
path = "/products/ace-project-management-software/*"