[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[edge_functions]]
function = "redirect"
path = "/web-development"
[[edge_functions]]
function = "redirect"
path = "/web-development/*"

[[edge_functions]]
function = "redirect"
path = "/acecms"
[[edge_functions]]
function = "redirect"
path = "/acecms/*"

[[edge_functions]]
function = "redirect"
path = "/graphic-design"
[[edge_functions]]
function = "redirect"
path = "/graphic-design/*"
