[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

# Edge Function routes
[[edge_functions]]
function = "redirect"
path = "/acecms"
[[edge_functions]]
function = "redirect"
path = "/acecms/*"

[[edge_functions]]
function = "redirect"
path = "/web-development"
[[edge_functions]]
function = "redirect"
path = "/web-development/*"

[[edge_functions]]
function = "redirect"
path = "/acemrp"
[[edge_functions]]
function = "redirect"
path = "/acemrp/*"

[[edge_functions]]
function = "redirect"
path = "/aceplm"
[[edge_functions]]
function = "redirect"
path = "/aceplm/*"
